const screen_guide_data = [
  "Move to a clear space before beginning",
  "Before beginning breathing exercises...",
  "... we will guide you to rduce tension in your body",
  "Start making a fist, squeezing your hand tightly",
  "After a few seconds, open your fist one finger at a time",
  "Focus on feeling the tension leaving your fingers",
  "Next, repeat this process with your other hand",
  "If desired, repeat the process again with both hands",
  "Take notice of your body-where are you feeling tension?",
  "Common places include shoulders, legs, feet, and back",
  "Be sure to avoid places where you may have pain or injury",
  "Follow the same steps as before wherever you need to",
  "Squeeze and release body parts that you feel have tension",
  "When you feel ready, continue on to breathing exercises",
];
